matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "10"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint && cd ../demo-ng && npm run ci.tslint
    - stage: "WebPack Core"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode10
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
      script: cd demo && npm run build.plugin && npm i && tns build ios  --env.uglify
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 10
      script: cd demo && npm run build.plugin && npm i && tns build android  --env.uglify --env.snapshot
    - stage: "WebPack Angular"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode10
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
      script: cd demo-ng && npm run build.plugin && npm i && tns build ios  --env.uglify --env.aot
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 10
      script: cd demo-ng && npm run build.plugin && npm i && tns build android  --env.uglify --env.snapshot --env.aot

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
