matrix:
  include:
  - stage: "Lint"
    language: node_js
    os: linux
    node_js: "8"
    script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint && cd ../demo-ng && npm run ci.tslint
  - stage: "WebPack & Build"
    os: osx
    env:
    - WebPack="iOS"
    osx_image: xcode9.3
    language: node_js
    node_js: "8"
    jdk: oraclejdk8
    before_install:
    - travis_wait pod repo update --silent
    script:
    - cd demo && npm run build.plugin && npm i && tns build ios --bundle --env.uglify
    - cd ../publish
    - sh pack.sh
    - cp package/*.tgz ../demo-ng/package.tgz
    - cd ../demo-ng
    - sed -i -e 's/\"..\/src\"/"package.tgz"/g' package.json
    - npm i
    - tns build ios --bundle --env.uglify --env.aot
  - language: android
    os: linux
    env:
    - WebPack="Android"
    jdk: oraclejdk8
    before_install: nvm install 8.11.4
    script:
    - cd demo && npm run build.plugin && npm i && tns build android --bundle --env.uglify --env.snapshot
    - cd ../publish
    - sh pack.sh
    - cp package/*.tgz ../demo-ng/package.tgz
    - cd ../demo-ng
    - sed -i -e 's/\"..\/src\"/"package.tgz"/g' package.json
    - npm i
    - tns build android --bundle --env.uglify --env.aot
  - language: android
    env:
    - BuildAndroid="27"
    os: linux
    jdk: oraclejdk8
    before_install: nvm install 8
    script:
    - cd src && npm i && npm run tsc && cd ../demo && tns build android && cd ../demo-ng && tns build android
  - os: osx
    env:
    - BuildiOS="11"
    - Xcode="9.3"
    osx_image: xcode9.3
    language: node_js
    node_js: "8"
    jdk: oraclejdk8
    before_install:
    - travis_wait pod repo update --silent
    script:
    - cd src && npm i && npm run tsc && cd ../demo && tns build ios && cd ../demo-ng && tns build ios

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.2
  - build-tools-27.0.3
  - android-28
  - android-26
  - android-23
  - extra-android-m2repository

install:
- echo no | npm install -g nativescript
- tns usage-reporting disable
- tns error-reporting disable